# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Philip Siddhartha Thielges
description: "Hi I'm Philip, and I'm a Data Scientist. I have a bachelor's degree in physics, in which I specialized particularly in deep learning.  
"My portfolio focuses on interesting projects I've recently undertaken, with a strong emphasis on business impact. 
"Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Nordhorn, Germany"
resume_url: /docs/CV__Thielges_Philip.pdf
avatar_image: /img/IMG_0574.JPG

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/philip-thielges-304b201a5/" # Add your linkedln handle
github: "https://github.com/philip-thielges"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

